### ISSUE TITLE
trained model link is broken

### ISSUE THREAD

**Issue by ghost** [shi-jian/shapenet-intrinsics#5]
The trained model is not available. Could you please provide it again? Thanks.

**Comment by shi-jian** [comment]
@x7177214 
The server was down. Fixed now.

please note that:
1. the download link for the model is traind with 1m iters instead of 450k iters.
450k model is on [here](http://share.shijian.org.cn/shapenet/intrinsics/model_old.t7). However, it is trained with old version of torch. In 2016, torch modified its API for SpatialUpSampling... While most our results in the paper are based on the old model. New model with 1m iters is only provided for new API.
2. The shapenet.dll(mitsuba plugin) is compiled with vs2013 x64. However, it seems mitsuba official site provides a binary compiled with vs2010. So it is not compatible. I uploaded a full binary package on [here](http://share.shijian.org.cn/shapenet/render/mitsuba-shapenet.zip). It might be useful.

**Comment by ghost** [comment]
I will take a try. Thank you!
